# -*- coding: utf-8 -*-
"""model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BAH09XdQ7KM7UL4kCL4OkSUSk4EI3GpB
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense,Flatten,Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report,confusion_matrix
import pandas as pd
import seaborn as sns

data_dir='/content/drive/MyDrive/data'
train_dir=os.path.join(data_dir,'train')
test_dir=os.path.join(data_dir,'test')

train_datagen=ImageDataGenerator(
    rescale=1./225,rotation_range=25,width_shift_range=0.2,height_shift_range=0.2,shear_range=0.2,zoom_range=0.2,horizontal_flip=True,fill_mode='nearest'

)
test_datagen=ImageDataGenerator(rescale=1./225)
train_generator=train_datagen.flow_from_directory(
    train_dir,target_size=(224,224),batch_size=32,class_mode='binary'
)
test_generator=test_datagen.flow_from_directory(
    test_dir,target_size=(224,224),batch_size=32,class_mode='binary',shuffle=False
)

print("classes detectees:",train_generator.class_indices)
x_batch,y_batch=next(train_generator)
plt.figure(figsize=(10,10))
for i in range(9):
  plt.subplot(3,3,i+1)
  plt.imshow(x_batch[i])
  label="Malignant" if y_batch[i]==1 else "Benign"
  plt.title(label)
  plt.axis('off')
plt.suptitle("exemples d'image du jeu d'entrainement ,fontsize=14")
plt.show

base_model=VGG16(weights='imagenet',include_top=False,input_shape=(224,224,3))
for layer in base_model.layers:
  layer.trainable=False
x=Flatten()(base_model.output)
x=Dense(256,activation='relu')(x)
x=Dropout(0.5)(x)
output=Dense(1,activation='sigmoid')(x)
model=Model(inputs=base_model.input,outputs=output)
model.compile(optimizer=Adam(learning_rate=0.0001),loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

history=model.fit(
    train_generator,validation_data=test_generator,epochs=10
)
test_generator.reset()
y_pred=model.predict(test_generator)
y_pred=(y_pred>0.5).astype(int).ravel()
y_true=test_generator.classes
print("rapport de classification")
print(classification_report(y_true,y_pred,target_names=['Benign','Malignant']))

cm=confusion_matrix(y_true,y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm,annot=True,fmt='d',cmap='Blues',xticklabels=['benign','malignant'],yticklabels=['benign','malignant'])
plt.xlabel('predit')
plt.ylabel('reel')
plt.title('matrice de confusion-VGG16')
plt.show()

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'],label='entrainement')
plt.plot(history.history['val_accuracy'],label='validation')
plt.legend()
plt.title("evaluation de la precision")

plt.subplot(1,2,2)
plt.plot(history.history['loss'],label='entrainement')
plt.plot(history.history['val_loss'],label='validation')
plt.legend()
plt.title("evaluation de la perte")
plt.show()
model_path='/content/drive/MyDrive/vgg16_malignant_vs_benign.h5'
model.save(model_path)
print(f"modele sauvegarder avec succes:{model_path}")

import random
import tensorflow as tf

filenames=test_generator.filenames
true_classes=test_generator.classes
class_labels=list(test_generator.class_indices.keys())
sample_indices=random.sample(range(len(filenames)),9)
plt.figure(figsize=(10,10))
for i,indx in enumerate(sample_indices):
  img_path=os.path.join(test_dir,filenames[indx])
  img=tf.keras.preprocessing.image.load_img(img_path,target_size=(224,224))
  img_array=tf.keras.preprocessing.image.img_to_array(img)/225.0
  img_array=np.expand_dims(img_array,axis=0)
  prediction=model.predict(img_array)
  predicted_label="malignant" if prediction>0.5 else "benign"
  actuel_label=class_labels[true_classes[indx]]
  plt.subplot(3,3,i+1)
  plt.imshow(img)
  plt.title(f"actuel:{actuel_label}\npredit:{predicted_label}")
  plt.axis('off')
  plt.suptitle("actuel vs predicted (VGG16)",fontsize=14)
  plt.tight_layout()
  plt.show()